version: '3.7'

services:
  texstudio:
    container_name: texstudio
    image: texstudio:0.0.1
    user: $UID:$GID
    entrypoint: ["/usr/bin/texstudio"]
    environment:
      DISPLAY: "${DISPLAY}"
    stdin_open: true
    volumes:
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
      # Mount you sources!
      - "$MOUNT_DIR:/data"
    init: true
